name: Cleanup old nightly packages

on:
  workflow_dispatch:

jobs:
  delete-old-nightlies:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete nightly packages older than the latest 7 versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: |
            pORM.Core
            pORM.Data
            pORM.Mapping
            pORM.Extensions
            pORM.Mysql
          package-type: nuget
          min-versions-to-keep: 7
          delete-only-pre-release-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
