name: Publish nightly build to GitHub Packages

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '0 2 * * *'  # every day at 2 AM UTC

jobs:
  publish-nightly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-build

      - name: Generate Nightly Version
        id: version
        run: |
          BASE_VERSION=$(grep '<Version>' src/pORM.Core/pORM.Core.csproj | sed -E 's/.*<Version>(.*)<\/Version>.*/\1/')
          NIGHTLY_TAG="nightly.$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
          echo "NIGHTLY_VERSION=${BASE_VERSION}-${NIGHTLY_TAG}" >> $GITHUB_ENV
          echo "version=${BASE_VERSION}-${NIGHTLY_TAG}" >> $GITHUB_OUTPUT

      - name: Pack Nightly
        run: |
          dotnet pack src/pORM.Core/pORM.Core.csproj \
            --configuration Release \
            --no-build \
            --output ./nupkg \
            /p:Version=${{ env.NIGHTLY_VERSION }}

      - name: Push to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key ${{ secrets.GITHUB_TOKEN }}
