name: Publish stable build

on:
  workflow_dispatch:
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'src/**/*.csproj'
#       - 'Directory.Packages.props'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-build

      - name: Extract version from .csproj
        id: version
        run: |
          VERSION=$(grep '<Version>' src/pORM.Core/pORM.Core.csproj | sed -E 's/.*<Version>(.*)<\/Version>.*/\1/')
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if version already exists on NuGet
        id: check_nuget
        run: |
          EXISTS=$(curl -s https://api.nuget.org/v3-flatcontainer/porm.core/${{ steps.version.outputs.version }}/porm.core.${{ steps.version.outputs.version }}.nupkg --head | head -n 1 | grep "200" || true)
          echo "exists=$EXISTS" >> $GITHUB_OUTPUT

      - name: Pack
        if: steps.check_nuget.outputs.exists == ''
        run: dotnet pack src/pORM.Core/pORM.Core.csproj --configuration Release --no-build --output ./nupkg

      - name: Push to NuGet
        if: steps.check_nuget.outputs.exists == ''
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
