name: Publish nightly build

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  publish-nightly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-build

      - name: Generate Nightly Version
        id: version
        run: |
          BASE_VERSION=$(grep '<Version>' Directory.Build.props | sed -E 's/.*<Version>(.*)<\/Version>.*/\1/')
          NIGHTLY_TAG="nightly.$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
          echo "NIGHTLY_VERSION=${BASE_VERSION}-${NIGHTLY_TAG}" >> $GITHUB_ENV
          echo "version=${BASE_VERSION}-${NIGHTLY_TAG}" >> $GITHUB_OUTPUT

      - name: Publish pORM.Core
        run: |
          dotnet pack src/pORM.Core/pORM.Core.csproj --configuration Release --no-build --output ./nupkg /p:Version=${{ env.NIGHTLY_VERSION }} /p:Nightly=true
          dotnet nuget push ./nupkg/pORM.Core.*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GH_API_KEY }} \
            

      - name: Publish pORM.Data
        run: |
          dotnet pack src/pORM.Data/pORM.Data.csproj --configuration Release --no-build --output ./nupkg /p:Version=${{ env.NIGHTLY_VERSION }} /p:Nightly=true
          dotnet nuget push ./nupkg/pORM.Data.*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GH_API_KEY }}

      - name: Publish pORM.Mapping
        run: |
          dotnet pack src/pORM.Mapping/pORM.Mapping.csproj --configuration Release --no-build --output ./nupkg /p:Version=${{ env.NIGHTLY_VERSION }} /p:Nightly=true
          dotnet nuget push ./nupkg/pORM.Mapping.*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GH_API_KEY }}

      - name: Publish pORM.Extensions
        run: |
          dotnet pack src/pORM.Extensions/pORM.Extensions.csproj --configuration Release --no-build --output ./nupkg /p:Version=${{ env.NIGHTLY_VERSION }} /p:Nightly=true
          dotnet nuget push ./nupkg/pORM.Extensions.*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GH_API_KEY }}

      - name: Publish pORM.MySql
        run: |
          dotnet pack Providers/pORM.Mysql/pORM.Mysql.csproj --configuration Release --no-build --output ./nupkg /p:Version=${{ env.NIGHTLY_VERSION }} /p:Nightly=true
          dotnet nuget push ./nupkg/pORM.Mysql.*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GH_API_KEY }}
